### ISSUE TITLE
SIGABRT during `make release` packaging

### ISSUE THREAD

**Issue by chris-counteractive** [counteractive/o365beat#32]
An error occurs during `make release`, as shown below.  This does not appear to break the build, but requires some research into its root cause.  It was introduced after modifying the magefile to fix #9, but it still occurs even after removing that new code.  It existed before and after the update to libbeat 7.5.1, and after a full re-pull of all the requisite docker images.

It does not happen when building the project locally (i.e., `make` vs. `make release`), it appears to occur during the packaging phase.

```
>> package: Building o365beat type=zip for platform=windows/amd64
>> package: Building o365beat type=rpm for platform=linux/amd64
>> package: Building o365beat type=tar.gz for platform=linux/amd64
>> package: Building o365beat type=deb for platform=linux/amd64
>> package: Building o365beat type=tar.gz for platform=darwin/amd64
>> package: Building o365beat type=tar.gz for platform=linux/386
>> package: Building o365beat type=deb for platform=linux/386
>> package: Building o365beat type=rpm for platform=linux/386
>> package: Building o365beat type=docker for platform=linux/amd64
>> package: Building o365beat type=zip for platform=windows/386
free(): invalid pointer
SIGABRT: abort
PC=0x7f5d1ab67e97 m=0 sigcode=18446744073709551610
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4afd50, 0xc420055cc0, 0xc420055ce8)
        /usr/lib/go-1.8/src/runtime/cgocall.go:131 +0xe2 fp=0xc420055c90 sp=0xc420055c50
github.com/docker/docker-credential-helpers/secretservice._Cfunc_free(0x110ada0)
        github.com/docker/docker-credential-helpers/secretservice/_obj/_cgo_gotypes.go:111 +0x41 fp=0xc420055cc0 sp=0xc420055c90
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List.func5(0x110ada0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:96 +0x60 fp=0xc420055cf8 sp=0xc420055cc0
github.com/docker/docker-credential-helpers/secretservice.Secretservice.List(0x0, 0x756060, 0xc420016370)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go:97 +0x217 fp=0xc420055da0 sp=0xc420055cf8
github.com/docker/docker-credential-helpers/secretservice.(*Secretservice).List(0x77e548, 0xc420055e88, 0x410022, 0xc4200162d0)
        <autogenerated>:4 +0x46 fp=0xc420055de0 sp=0xc420055da0
github.com/docker/docker-credential-helpers/credentials.List(0x756ba0, 0x77e548, 0x7560e0, 0xc42000e018, 0x0, 0x10)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:145 +0x3e fp=0xc420055e68 sp=0xc420055de0
github.com/docker/docker-credential-helpers/credentials.HandleCommand(0x756ba0, 0x77e548, 0x7fff19bb54db, 0x4, 0x7560a0, 0xc42000e010, 0x7560e0, 0xc42000e018, 0x40e398, 0x4d35c0)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:60 +0x16d fp=0xc420055ed8 sp=0xc420055e68
github.com/docker/docker-credential-helpers/credentials.Serve(0x756ba0, 0x77e548)
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/obj-x86_64-linux-gnu/src/github.com/docker/docker-credential-helpers/credentials/credentials.go:41 +0x1cb fp=0xc420055f58 sp=0xc420055ed8
main.main()
        /build/golang-github-docker-docker-credential-helpers-cMhSy1/golang-github-docker-docker-credential-helpers-0.5.0/secretservice/cmd/main_linux.go:9 +0x4f fp=0xc420055f88 sp=0xc420055f58
runtime.main()
        /usr/lib/go-1.8/src/runtime/proc.go:185 +0x20a fp=0xc420055fe0 sp=0xc420055f88
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420055fe8 sp=0xc420055fe0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/go-1.8/src/runtime/asm_amd64.s:2197 +0x1
```

**Comment by chris-counteractive** [comment]
Looks like this relates to the version of the `golang-docker-credential-helpers` package on the build system.  More details at https://github.com/docker/docker-credential-helpers/issues/104.

**Comment by chris-counteractive** [comment]
It seems like I can work around this by not having `docker-compose` installed on the build system.

**Comment by chris-counteractive** [comment]
This doesn't affect a successful build, and is fixed by removing `docker-compose`.  Closing: it's annoying, but unrelated to the beat _per se_.
